### ISSUE TITLE
stack doesn't "know how to install GHC on your system configuration" even though ghc 8.6.5 is available

### ISSUE THREAD

**Issue by hhefesto** [tbenst/purescript-nix-example#2]
Hi!

Ran into some trouble in `yarn install`.

This is the error msg and some extras:

```
╭─hhefesto@Olimpo ~/src/purescript-nix-example ‹master*› 
╰─$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3f928282c0989232e425d26f0302120a8c7218b.tar.gz shell.nix
these derivations will be built:
  /nix/store/82b7vv8g0ps07j5z7bapb101wwv19bvz-dhall-json-simple.drv
  /nix/store/hdj3gfz414073a2avr7czpg4wps6mvp8-spago.drv
  /nix/store/8ip7n9zyfmb3ch1vfi2wsx098kygs12y-spago2nix.drv
these paths will be fetched (5.32 MiB download, 26.73 MiB unpacked):
  /nix/store/0vcqyg4cadpns1l935h18ram5ngqqsgq-aws-sdk-cpp-1.7.90
  /nix/store/4jka6m0hfsfm4hdjg0irjirwpyhk8hks-libsodium-1.0.18
  /nix/store/656xbh6b5i5d4iqjqnbza2z6xvbgaxz4-brotli-1.0.7-lib
  /nix/store/6hw4wkqbaf4zldnhmmncx3bz72map754-aws-c-common-0.3.11
  /nix/store/6p0003sq7knmcnsir97h34ixbyj75n5n-editline-1.16.1
  /nix/store/apzd08v6qq95ppvkr5jp9m516q1nys4s-readline-7.0p5
  /nix/store/bdxibm4b8g761lw9arz1a8sslm71gmkv-libseccomp-2.4.1-lib
  /nix/store/d2482p2v2dlrwr8k0xjrl1sd6njym720-hook
  /nix/store/fhqy9zsxm6m8dyy79wcrhh40zlxzywma-hook
  /nix/store/fpl4264jl7sczq7qpn04yc52gvq1195y-bash-interactive-4.4-p23-info
  /nix/store/gp828m4vmvm17r2zx6j7z0k46qng40zw-gmp-6.1.2-dev
  /nix/store/iq425ly3sldmnr6rcnj5x3xi7pajin1f-ncurses-6.1-20190112-abi5-compat-dev
  /nix/store/kmzigdidq84lhrkwgm435m62x72xqvxh-bash-interactive-4.4-p23-dev
  /nix/store/l82fyhdx82nayr62ww8nsc8xc84m1x3j-ncurses-6.1-20190112-abi5-compat-man
  /nix/store/n8lw8n04d8jlk4zkqrrwnm9a1bx9mxrn-nix-2.3.1-man
  /nix/store/qy7pwiwacil139ah1jny1zl1182ydkjf-busybox-1.31.1-x86_64-unknown-linux-musl
  /nix/store/rcmxqwxgkqip16gq7c6j03wjp4xc6nnr-nix-prefetch-git
  /nix/store/sm740vh74gh7r8ww6q3wf067xkq1nb64-nix-2.3.1
  /nix/store/vs7zapqwngylvpydpv5dg3gk1va8dj8w-bash-interactive-4.4-p23
  /nix/store/w4lsjhdlw9gjv9j1lps8g6m1w3w9mprb-bash-interactive-4.4-p23-man
  /nix/store/yjxj890hgn8lz9nxjlppnsiq43isr8h4-bash-interactive-4.4-p23-doc
  /nix/store/yw05vwhc62g9m12ylvp1i2fb0jwilfls-boehm-gc-8.0.4
copying path '/nix/store/fpl4264jl7sczq7qpn04yc52gvq1195y-bash-interactive-4.4-p23-info' from 'https://cache.nixos.org'...
copying path '/nix/store/yjxj890hgn8lz9nxjlppnsiq43isr8h4-bash-interactive-4.4-p23-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/w4lsjhdlw9gjv9j1lps8g6m1w3w9mprb-bash-interactive-4.4-p23-man' from 'https://cache.nixos.org'...
copying path '/nix/store/apzd08v6qq95ppvkr5jp9m516q1nys4s-readline-7.0p5' from 'https://cache.nixos.org'...
copying path '/nix/store/6hw4wkqbaf4zldnhmmncx3bz72map754-aws-c-common-0.3.11' from 'https://cache.nixos.org'...
copying path '/nix/store/yw05vwhc62g9m12ylvp1i2fb0jwilfls-boehm-gc-8.0.4' from 'https://cache.nixos.org'...
copying path '/nix/store/656xbh6b5i5d4iqjqnbza2z6xvbgaxz4-brotli-1.0.7-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/vs7zapqwngylvpydpv5dg3gk1va8dj8w-bash-interactive-4.4-p23' from 'https://cache.nixos.org'...
copying path '/nix/store/qy7pwiwacil139ah1jny1zl1182ydkjf-busybox-1.31.1-x86_64-unknown-linux-musl' from 'https://cache.nixos.org'...
copying path '/nix/store/0vcqyg4cadpns1l935h18ram5ngqqsgq-aws-sdk-cpp-1.7.90' from 'https://cache.nixos.org'...
copying path '/nix/store/6p0003sq7knmcnsir97h34ixbyj75n5n-editline-1.16.1' from 'https://cache.nixos.org'...
copying path '/nix/store/gp828m4vmvm17r2zx6j7z0k46qng40zw-gmp-6.1.2-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/d2482p2v2dlrwr8k0xjrl1sd6njym720-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/bdxibm4b8g761lw9arz1a8sslm71gmkv-libseccomp-2.4.1-lib' from 'https://cache.nixos.org'...
copying path '/nix/store/4jka6m0hfsfm4hdjg0irjirwpyhk8hks-libsodium-1.0.18' from 'https://cache.nixos.org'...
copying path '/nix/store/fhqy9zsxm6m8dyy79wcrhh40zlxzywma-hook' from 'https://cache.nixos.org'...
copying path '/nix/store/l82fyhdx82nayr62ww8nsc8xc84m1x3j-ncurses-6.1-20190112-abi5-compat-man' from 'https://cache.nixos.org'...
copying path '/nix/store/n8lw8n04d8jlk4zkqrrwnm9a1bx9mxrn-nix-2.3.1-man' from 'https://cache.nixos.org'...
building '/nix/store/82b7vv8g0ps07j5z7bapb101wwv19bvz-dhall-json-simple.drv'...
unpacking sources
unpacking source archive /nix/store/hxjvw76iax0ly65fqz2qz66xkl23308n-dhall-json-1.4.1-x86_64-linux.tar.bz2
source root is bin
setting SOURCE_DATE_EPOCH to timestamp 1569383860 of file bin/yaml-to-dhall
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/2yjqbfp5ps5vvz6g83ycqyyba0yj985y-dhall-json-simple
shrinking /nix/store/2yjqbfp5ps5vvz6g83ycqyyba0yj985y-dhall-json-simple/bin/dhall-to-json
cannot find section .dynamic
strip is /nix/store/a9ms1pkj00sgssxqr2cvryv3h5fki4an-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/2yjqbfp5ps5vvz6g83ycqyyba0yj985y-dhall-json-simple/bin
patching script interpreter paths in /nix/store/2yjqbfp5ps5vvz6g83ycqyyba0yj985y-dhall-json-simple
checking for references to /build/ in /nix/store/2yjqbfp5ps5vvz6g83ycqyyba0yj985y-dhall-json-simple...
cannot find section .dynamic
copying path '/nix/store/kmzigdidq84lhrkwgm435m62x72xqvxh-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
copying path '/nix/store/iq425ly3sldmnr6rcnj5x3xi7pajin1f-ncurses-6.1-20190112-abi5-compat-dev' from 'https://cache.nixos.org'...
building '/nix/store/hdj3gfz414073a2avr7czpg4wps6mvp8-spago.drv'...
copying path '/nix/store/sm740vh74gh7r8ww6q3wf067xkq1nb64-nix-2.3.1' from 'https://cache.nixos.org'...
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/67a9627vw72ixa8jc6c94ma614n8ygaj-spago
shrinking /nix/store/67a9627vw72ixa8jc6c94ma614n8ygaj-spago/bin/spago
patching script interpreter paths in /nix/store/67a9627vw72ixa8jc6c94ma614n8ygaj-spago
checking for references to /build/ in /nix/store/67a9627vw72ixa8jc6c94ma614n8ygaj-spago...
copying path '/nix/store/rcmxqwxgkqip16gq7c6j03wjp4xc6nnr-nix-prefetch-git' from 'https://cache.nixos.org'...
building '/nix/store/8ip7n9zyfmb3ch1vfi2wsx098kygs12y-spago2nix.drv'...
unpacking sources
unpacking source archive /nix/store/kyi7r526mkc2s6p7x9fp58cnaddjjcm9-xdyq61gyi4wd5m4ajflzwywpsdgflplw-source
source root is xdyq61gyi4wd5m4ajflzwywpsdgflplw-source
patching sources
configuring
no configure script, doing nothing
building
no Makefile, doing nothing
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/p6sypslnkggkqa67sj2w7bqvpim5fpqb-spago2nix
strip is /nix/store/a9ms1pkj00sgssxqr2cvryv3h5fki4an-binutils-2.31.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/p6sypslnkggkqa67sj2w7bqvpim5fpqb-spago2nix/bin
patching script interpreter paths in /nix/store/p6sypslnkggkqa67sj2w7bqvpim5fpqb-spago2nix
checking for references to /build/ in /nix/store/p6sypslnkggkqa67sj2w7bqvpim5fpqb-spago2nix...

[nix-shell:~/src/purescript-nix-example]$ yarn install
yarn install v1.19.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⡀ waiting...
[5/5] ⡀ parcel-bundler
[3/5] ⢀ purescript
[4/5] ⢀ spago
error /home/hhefesto/src/purescript-nix-example/node_modules/purescript: Command failed.
Exit code: 1
Command: install-purescript --purs-ver=0.13.5
Arguments: 
Directory: /home/hhefesto/src/purescript-nix-example/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.13.5 binary is provided for linux (2s)
[ SUCCESS ] Download the prebuilt PureScript binary (37s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: spawn /home/hhefesto/src/purescript-nix-example/node_modules/purescript/purs.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

↓ Fallback: building from source

[ SUCCESS ] Check if 'stack' command is available
[ RUNNING ] command: stack setup
  Downloading lts-13.26 build plan ...
[ SUCCESS ] Download the PureScript 0.13.5 source (3s)
  Downloaded lts-13.26 build plan.
  I don't know how to install GHC on your system configuration, please install manually
[ FAILURE ] Ensure the appropriate GHC is installed (5s)
Error: Command failed with exit code 1 (EPERM): stack --allow-different-user setup





[nix-shell:~/src/purescript-nix-example]$ which ghc
/home/hhefesto/.nix-profile/bin/ghc

[nix-shell:~/src/purescript-nix-example]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5

[nix-shell:~/src/purescript-nix-example]$ stack --version
1.9.3 x86_64 hpack-0.31.2
```

from the error I figured that `stack` with lts-13.26 is trying to install ghc-8.6.5, but fails, even though it is already available as shown by `ghc --version`

How can I configure the `stack` that purescript uses to know how to install ghc-8.6.5 in a NixOS enviroment?

Thanks in advanced   : )

**Comment by tbenst** [comment]
Huh, I couldn't reproduce. I don't understand `[ FAILURE ] Verify the prebuilt binary works correctly`

Could you please try:
```
>  git reset --hard HEAD # will remove any local changes
`nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3f928282c0989232e425d26f0302120a8c7218b.tar.gz --pure shell.nix`
$ yarn clean
$ yarn install
``` 

The `--pure` flag will reduce chance that your PATH is interfering. If that doesn't work, what OS are you running on?

**Comment by hhefesto** [comment]
Still no luck :(

Now it got angry that there is no stack:

```
╭─hhefesto@Olimpo ~/src/purescript-nix-example ‹master*› 
╰─$ git reset --hard HEAD                                                                                                                                           1 ↵
HEAD is now at 854868d fix bundle command
╭─hhefesto@Olimpo ~/src/purescript-nix-example ‹master› 
╰─$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3f928282c0989232e425d26f0302120a8c7218b.tar.gz --pure shell.nix

[nix-shell:~/src/purescript-nix-example]$ yarn clean
yarn run v1.19.2
$ rm -rf output .spago dist/* node_modules output .cache .spago2nix
Done in 0.42s.

[nix-shell:~/src/purescript-nix-example]$ yarn install
yarn install v1.19.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⠐ waiting...
[5/5] ⠐ parcel-bundler
[3/5] ⠈ purescript
[4/5] ⠈ spago
error /home/hhefesto/src/purescript-nix-example/node_modules/purescript: Command failed.
Exit code: 1
Command: install-purescript --purs-ver=0.13.5
Arguments: 
Directory: /home/hhefesto/src/purescript-nix-example/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.13.5 binary is provided for linux (2s)
[ SUCCESS ] Download the prebuilt PureScript binary (34s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: spawn /home/hhefesto/src/purescript-nix-example/node_modules/purescript/purs.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

↓ Fallback: building from source

[ FAILURE ] Check if 'stack' command is available
Error: Command failed with exit code 2 (ENOENT): stack --allow-different-user --numeric-version
spawn stack ENOENT





[nix-shell:~/src/purescript-nix-example]$ yarn full-clean
yarn run v1.19.2
$ rm -rf node_modules output .spago dist/* *.lock spago-packages.nix yarn.nix .spago2nix .cache spago.dhall packages.dhall
Done in 0.43s.

[nix-shell:~/src/purescript-nix-example]$ yarn install
yarn install v1.19.2
info No lockfile found.
[1/4] Resolving packages...
warning parcel-bundler > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning parcel-bundler > babylon-walk > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⢀ waiting...
[5/5] ⢀ parcel-bundler
[3/5] ⢀ purescript
[4/5] ⢀ spago
error /home/hhefesto/src/purescript-nix-example/node_modules/purescript: Command failed.
Exit code: 1
Command: install-purescript --purs-ver=0.13.6
Arguments: 
Directory: /home/hhefesto/src/purescript-nix-example/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.13.6 binary is provided for linux (1s)
[ SUCCESS ] Download the prebuilt PureScript binary (18s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: spawn /home/hhefesto/src/purescript-nix-example/node_modules/purescript/purs.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

↓ Fallback: building from source

[ FAILURE ] Check if 'stack' command is available
Error: Command failed with exit code 2 (ENOENT): stack --allow-different-user --numeric-version
spawn stack ENOENT





[nix-shell:~/src/purescript-nix-example]$ which stack 
The program ‘which’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.busybox
  nix-env -iA nixos.debianutils
  nix-env -iA nixos.toybox
  nix-env -iA nixos.which

[nix-shell:~/src/purescript-nix-example]$ stack --version
The program ‘stack’ is currently not installed. You can install it by typing:
  nix-env -iA nixos.stack

[nix-shell:~/src/purescript-nix-example]$ 
```

I am on NixOS 19.09. [This](https://gist.github.com/hhefesto/2f3a25dc4ffa4ab4fd746746891ac6e9) is my configuration.nix file.

**Comment by hhefesto** [comment]
I added stack to buildInputs on shell.nix and got the same initial error:

```
╭─hhefesto@Olimpo ~/src/purescript-nix-example ‹master*› 
╰─$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3f928282c0989232e425d26f0302120a8c7218b.tar.gz --pure shell.nix                                  1 ↵
these paths will be fetched (3.68 MiB download, 25.15 MiB unpacked):
  /nix/store/w1yvgmsydr5fpk39xwdw9sibjp7gh7i2-stack-2.1.3.1
copying path '/nix/store/w1yvgmsydr5fpk39xwdw9sibjp7gh7i2-stack-2.1.3.1' from 'https://cache.nixos.org'...

[nix-shell:~/src/purescript-nix-example]$ yarn install
yarn install v1.19.2
info No lockfile found.
[1/4] Resolving packages...
warning parcel-bundler > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning parcel-bundler > babylon-walk > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⡀ waiting...
[5/5] ⡀ parcel-bundler
[3/5] ⡀ purescript
[4/5] ⡀ spago
error /home/hhefesto/src/purescript-nix-example/node_modules/purescript: Command failed.
Exit code: 1
Command: install-purescript --purs-ver=0.13.6
Arguments: 
Directory: /home/hhefesto/src/purescript-nix-example/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.13.6 binary is provided for linux (2s)
[ SUCCESS ] Download the prebuilt PureScript binary (11s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: spawn /home/hhefesto/src/purescript-nix-example/node_modules/purescript/purs.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

↓ Fallback: building from source

[ SUCCESS ] Check if 'stack' command is available
[ SUCCESS ] Download the PureScript 0.13.6 source (4s)
[ RUNNING ] command: stack setup
  Specified file "README.md" for extra-source-files does not exist
  Specified file "INSTALL.md" for extra-source-files does not exist
  Specified file "CONTRIBUTORS.md" for extra-source-files does not exist
  Specified file "CONTRIBUTING.md" for extra-source-files does not exist
  I don't know how to install GHC on your system configuration, please install manually
[ FAILURE ] Ensure the appropriate GHC is installed (30s)
Error: Command failed with exit code 1 (EPERM): stack --allow-different-user setup





[nix-shell:~/src/purescript-nix-example]$ 

```

**Comment by hhefesto** [comment]
Maybe this helps?

```
╭─hhefesto@Olimpo ~/src/purescript-nix-example ‹master*› 
╰─$ nix-channel --list                                                                                                                                            127 ↵
nixos https://nixos.org/channels/nixos-19.09
nixos-19.03 https://nixos.org/channels/nixos-19.03
nixos-1909 https://nixos.org/channels/nixos-19.09
```

**Comment by tbenst** [comment]
@hhefesto what architecture are you on? x86_64? What’s your processor? On the machines I’ve test the pre-built binary runs, so stack/GHC isn’t required. I think you’re running into https://github.com/purescript/purescript/issues/3544

If you try the bootstrap steps, maybe you can make a different yarn.lock file that will pull binaries that work on your machine. The other approach, as you suggest, is to add stack/ghc as buildinputs so you can build purescript. I’m not entirely sure if this alone is sufficient as haven’t needed to do this on the architectures I use.

**Comment by hhefesto** [comment]
```
╭─hhefesto@Olimpo ~/src/purescript-nix-example ‹master*› 
╰─$ uname -m
x86_64
╭─hhefesto@Olimpo ~/src/purescript-nix-example ‹master*› 
╰─$ cat /proc/cpuinfo | grep 'model name' | uniq
model name	: Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz
```

**Comment by hhefesto** [comment]
> If you try the bootstrap steps, maybe you can make a different yarn.lock file that will pull binaries that work on your machine.

will try this, but later today.

Thanks for all your time! I'll keep you posted.

**Comment by hhefesto** [comment]
Adding `stack` and `ghc` to build inputs did not work:

```
╭─hhefesto@Olimpo ~/src/purescript-nix-example ‹master*› 
╰─$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3f928282c0989232e425d26f0302120a8c7218b.tar.gz --pure shell.nix                                127 ↵

[nix-shell:~/src/purescript-nix-example]$ which ghc
The program ‘which’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.busybox
  nix-env -iA nixos.debianutils
  nix-env -iA nixos.toybox
  nix-env -iA nixos.which

[nix-shell:~/src/purescript-nix-example]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5

[nix-shell:~/src/purescript-nix-example]$ yarn clean
yarn run v1.19.2
$ rm -rf output .spago dist/* node_modules output .cache .spago2nix
Done in 0.40s.

[nix-shell:~/src/purescript-nix-example]$ yarn install
yarn install v1.19.2
info No lockfile found.
[1/4] Resolving packages...
warning parcel-bundler > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning parcel-bundler > babylon-walk > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[-/5] ⠂ waiting...
[5/5] ⠂ parcel-bundler
[3/5] ⠂ purescript
[4/5] ⠂ spago
error /home/hhefesto/src/purescript-nix-example/node_modules/purescript: Command failed.
Exit code: 1
Command: install-purescript --purs-ver=0.13.6
Arguments: 
Directory: /home/hhefesto/src/purescript-nix-example/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.13.6 binary is provided for linux (1s)
[ SUCCESS ] Download the prebuilt PureScript binary (23s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: spawn /home/hhefesto/src/purescript-nix-example/node_modules/purescript/purs.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

↓ Fallback: building from source

[ SUCCESS ] Check if 'stack' command is available
[ SUCCESS ] Download the PureScript 0.13.6 source (2s)
[ RUNNING ] command: stack setup
  Specified file "tests/support/setup-win.cmd" for extra-source-files does not exist
  Specified pattern "tests/support/pscide/src/**/*.js" for extra-source-files does not match any files
  Specified pattern "tests/support/pscide/src/**/*.fail" for extra-source-files does not match any files
  Specified file "README.md" for extra-source-files does not exist
  Specified file "INSTALL.md" for extra-source-files does not exist
  Specified file "CONTRIBUTORS.md" for extra-source-files does not exist
  Specified file "CONTRIBUTING.md" for extra-source-files does not exist
  I don't know how to install GHC on your system configuration, please install manually
[ FAILURE ] Ensure the appropriate GHC is installed (1s)
Error: Command failed with exit code 1 (EPERM): stack --allow-different-user setup





[nix-shell:~/src/purescript-nix-example]$ 
```

I checked and purescript 0.13.6 uses lts-13.26 which uses ghc 8.6.5, so the buldInput ghc is the correct one.

Maybe `stack` has to be a specific version?

**Comment by hhefesto** [comment]
will try the bootstrap next

**Comment by hhefesto** [comment]
Still no luck (this output is with `stack` and `ghc` added to buildInputs):

```
╭─hhefesto@Olimpo ~/src/purescript-nix-example ‹master*› 
╰─$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3f928282c0989232e425d26f0302120a8c7218b.tar.gz --pure shell.nix                                  1 ↵

[nix-shell:~/src/purescript-nix-example]$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5

[nix-shell:~/src/purescript-nix-example]$ stack --version
2.1.3.1 x86_64 hpack-0.33.0

[nix-shell:~/src/purescript-nix-example]$ yarn full-clean
yarn run v1.19.2
$ rm -rf node_modules output .spago dist/* *.lock spago-packages.nix yarn.nix .spago2nix .cache spago.dhall packages.dhall
Done in 0.41s.

[nix-shell:~/src/purescript-nix-example]$ yarn bootstrap-nix
yarn run v1.19.2
$ yarn add --dev purescript spago parcel-bundler && yarn add http-server && yarn spago init && yarn spago install halogen && yarn2nix > yarn.nix && spago2nix generate
info No lockfile found.
[1/4] Resolving packages...
warning parcel-bundler > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning parcel-bundler > babylon-walk > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
[2/4] Fetching packages...
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/5] ⠐ purescript
[2/5] ⠐ spago
[-/5] ⠐ waiting...
[5/5] ⠐ parcel-bundler
error /home/hhefesto/src/purescript-nix-example/node_modules/purescript: Command failed.
Exit code: 1
Command: install-purescript --purs-ver=0.13.6
Arguments: 
Directory: /home/hhefesto/src/purescript-nix-example/node_modules/purescript
Output:
[ SUCCESS ] Check if a prebuilt 0.13.6 binary is provided for linux (945ms)
[ SUCCESS ] Download the prebuilt PureScript binary (2s)
[ FAILURE ] Verify the prebuilt binary works correctly
Error: spawn /home/hhefesto/src/purescript-nix-example/node_modules/purescript/purs.bin ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

↓ Fallback: building from source

[ SUCCESS ] Check if 'stack' command is available
[ SUCCESS ] Download the PureScript 0.13.6 source (2s)
[ RUNNING ] command: stack setup
  Specified file "README.md" for extra-source-files does not exist
  Specified file "INSTALL.md" for extra-source-files does not exist
  Specified file "CONTRIBUTORS.md" for extra-source-files does not exist
  Specified file "CONTRIBUTING.md" for extra-source-files does not exist
  I don't know how to install GHC on your system configuration, please install manually
[ FAILURE ] Ensure the appropriate GHC is installed (1s)
Error: Command failed with exit code 1 (EPERM): stack --allow-different-user setup




error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[nix-shell:~/src/purescript-nix-example]$ 
```

**Comment by tbenst** [comment]
@hhefesto my sincere apologies--I was able to reproduce on NixOS. Sorry about that.  `nix-build -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/d3f928282c0989232e425d26f0302120a8c7218b.tar.gz` works on both bust I must have only tested the nix-shell instructions on Ubuntu.

This should be fixed by https://github.com/tbenst/purescript-nix-example/commit/e8da6459851b56211ce69d291f2d566475123602. Do let me know if it works now?

**Comment by hhefesto** [comment]
No need for apologies!

Thank you for the time and for sharing : )

**Comment by hhefesto** [comment]
Worked perfectly

**Comment by tbenst** [comment]
awesome. let me know if anything else comes up
